### PR TITLE
Fix test cases failed, add new tests case, change some tests cases

### PR DESCRIPTION
**Pull request by N1neSun**
Because of the addition of eml judgment in pick.py, some test cases have been modified and new test cases have been added.

- Delete some magic in ident.
- change some test cases
- add new test case
- Fix failed test cases
- add pull_request in workflow

### CODE REVIEW

**Comment by N1neSun** [comment]
Sorry, because I accidentally merged the branches wrongly, which led to so many commits, I think the problem should be solved.

**Comment by doomedraven** [comment]
thank for adding pull request to git actions

**Comment by doomedraven** [comment]
thank you for fixing tests and this

**Comment by N1neSun** [comment]
I’m glad to be able to help you and this repository.

**Comment by doomedraven** [comment]
new version released in pypi

**Comment by N1neSun** [comment]
thanks a lot.

**Comment by doomedraven** [comment]
you did all the job, i just released, so thank you to you!

**Pull request merged**
