### PR TITLE
Add check for compressed format packege

### PR DESCRIPTION
**Pull request by N1neSun**
- Add magic judgment for compressed packages
- Fix gzip being judged as targzfile
- Add new tests for mgic judgment
- change some tests

### CODE REVIEW

**Comment by doomedraven** [comment]
thank you, one questions are those tests files malicious? if yes i think we will need to compress that with password so good safe browsing won't ban this repo due to stored malware

**Comment by N1neSun** [comment]
No, I just copied the other files in the test file and changed the suffix.

**Comment by doomedraven** [comment]
ah ok thanks

**Comment by doomedraven** [comment]
btw if you don't care in future would you mind to bump version so i can directly merge and release

**Comment by N1neSun** [comment]
ok, np :)

**Pull request merged**
