### PR TITLE
fix eml parsing and change the package determination

### PR DESCRIPTION
**Pull request by N1neSun**
I don't think that all the problems have been solved, but at least the problems I encountered have been solved. I will update when i encounter problems in the future.

- Added magic judgments for eml and jar, etc.
- The judgment method has been changed. At present, the magic judgment is performed first to prevent problems caused by incorrect suffix names in most cases.
- fix issues #18

### CODE REVIEW

**Comment by doomedraven** [comment]
i will release pip package today/tomorrow

**Comment by doomedraven** [comment]
i will check later whats failing to fix that and will push your stuff again

**Comment by N1neSun** [comment]
i am sorry, tomorrow i will check it,make sure pass all test case.

**Comment by doomedraven** [comment]
np :) im not sure why tests are not triggered here, but on any other pr

**Pull request merged**
