### PR TITLE
Set of CERT-Polska/sflock patches

### PR DESCRIPTION
**Pull request by psrok1**
Hi!

First of all, thank you for your development and maintenance of this fork. We have been doing the same work for https://github.com/CERT-Polska/karton-archive-extractor project (https://github.com/CERT-Polska/sflock), but your repository looks much more up-to-date, so it would be nice to sync our changes :slightly_smiling_face:. It would be better to keep all of these contributions in the original repository, but it looks to be completely abandoned.

Here is the set of commits that include some enhancements (mainly developed by @nazywam):
- `lzip` support (https://github.com/doomedraven/sflock/commit/3e90d2a06727c410af1c7088cfa3797344b801b8)
- Fixed py3 compatibility of `ace.AceFile` module (https://github.com/doomedraven/sflock/commit/0fd9abd101933c0b46e8dfcbe686a1bf8d53b27b)
- Update of zipjail binary (https://github.com/doomedraven/sflock/commit/0d9af8abfb2329931a11afa1797e81ad0809229f, better described here: https://github.com/hatching/sflock/issues/50)
- `.udf` extension included for UDF archives (`zip7.Zip7File`, https://github.com/doomedraven/sflock/commit/e1f68e96b072f3730f6ef1e4c252037be63702a6)
- `.gz` extension included for `zip7.GzipFile` (https://github.com/doomedraven/sflock/commit/b12f3505f2ea2a9a981021f2c9028696502632ca)

Currently karton-archive-extractor just embeds the sflock code directly in the package: https://github.com/CERT-Polska/karton-archive-extractor/tree/master/karton/archive_extractor/sflock. That's because there is no forked PyPi distribution that could be used as a dependency. If you decide someday to publish and distribute that fork under new name (`sflock2` :smiley:), you'll have our support :muscle:

### CODE REVIEW

**Comment by doomedraven** [comment]
Hello @psrok1 thank you, as far as I know hatching still doing dev of sflock but internally, so i guess sflock py3 will be released with upcoming cuckoov3, im forwarding new features to Rico to keep them notificated about new features.

pip package sound good, I will make it public today and ping you here about that

**Comment by doomedraven** [comment]
pip package done 
```
pip3 install SFlock2==0.3.15
https://pypi.org/project/SFlock2/0.3.15/#files
```

**Comment by doomedraven** [comment]
btw @psrok1 do you have any sample for that lzip to share? i would like to add it to unittests so we can ensure that tool works properly on future upgrades, strange that i didn't catch the ace problem before

**Comment by psrok1** [comment]
@doomedraven: Thanks! :heart:

> [...] hatching still doing dev of sflock but internally, so i guess sflock py3 will be released with upcoming cuckoov3, im forwarding new features to Rico to keep them notificated about new features.

Good news!

> do you have any sample for that lzip to share?

Sure, we have some testcases from Brushaloader campaign. I see that you have MWDB account, so you can download these files from our service:
`document3230.vbe.lz`: https://mwdb.cert.pl/file/bde2d06bb333f419fff16376fffce1ee434fa47ca57c4fcb80b2932f86892e40
`document3230.vbe`: https://mwdb.cert.pl/file/36ef14835a9d2c8fe241286a7758b7f849bdabccc698e7e78318abfb195dc1db

**Comment by doomedraven** [comment]
amazing i will add it a bit later, so we can have more proper testing and ensure proper work of the tool, thanks again for fixes and improvements

**Pull request merged**
